### ISSUE TITLE
Does Maker run in Linux?

### ISSUE THREAD

**Issue by MontyMoo** [digiwombat/TalkerMakerDeluxe#1]
I couldn't find a related website to this project so I hope you don't mind me posting in the issue section.

Firstly, thank you for your contribution. This is exactly what I was looking for and so far seems to be a solid little program. I'll take the time to try this out and see if I can find any bugs. 

Does TalkerMaker run in Linux? I noticed that the program is written in c#, if so have you tried it in Mono? I'm not particular experienced but I can see if I can work it out.

**Comment by digiwombat** [comment]
Sadly, I don't think it'll work unless I retool it to use a different UI framework. Mono doesn't implement WPF APIs other than those used in Silverlight, so it'd fail to build out that way I'm assuming. Silverlight was pretty limited in its implementation of WPF frameworks. WPF makes my front-end dev times quick to turn around, and it's tied into the GridLayout system (extends WPF Panel) that darnellp built, so tossing it out would be a ton of rewriting.

If it won't run with Mono 2.8+ or in Wine with Mono 2.8+ installed, you're probably out of luck. Still, I'll leave this open for now. Please come back and let me know how it went and if anything seems fixable, I'll try to patch in Mono build support. My Ubuntu VM got weird after a recent reformat, so I can't test it myself at the moment.

Worst case, I guess just run a Windows VM and run it in there. Haha. God, I feel bad suggesting that. If only Mono loved XAML the way I love XAML.

EDIT: Also, thanks in advance for any bug reports. Much appreciated.

**Comment by MontyMoo** [comment]
Thank you for your response.

I see now. As I understand Chatmapper uses the same framework. WPF has limited support in Mono and is unlikely to change in the foreseeable future. Maybe with this whole MS Studio Code thing they have just released but I think that is for browser and mobile apps, I don't know too much about that though. 

I'll try Maker in Wine tomorrow and will report back on what happens.  

Cheers
