### ISSUE TITLE
Hi! Does this have native ChatMapper import/export?

### ISSUE THREAD

**Issue by sciencefair200** [digiwombat/TalkerMakerDeluxe#13]
Hi! I'm working on a project that requires me to use ChatMapper and the interface in CM gives me migraines. I'm looking around for an alternative, and I stumbled on TalkerMaker! Is there any way to get TalkerMaker files into/out of ChatMapper easily?

Thanks!

**Comment by digiwombat** [comment]
Hey!

So this used to operate on the ChatMapper XML format with a different header, but owing to my deep distaste for XML, the program now only operates on JSON files. It CAN, however, export a "Dialogue System XML" file which is just a ChatMapper file. 

Currently, there's no import capability for those files. All the logic for importing an XML file was gutted out in 2.0 but if someone wanted to add it back in, the code is all in [XmlHandler.cs](https://github.com/digiwombat/TalkerMakerDeluxe/blob/37d2d2cdaed530c8184ff4e7951eacf9d3f9e692/TalkerMakerDeluxe/XMLHandler.cs). I welcome a pull request if anyone wants to slap that together.

It would need to be adapted to the new TalkerMakerDatabase class and that doesn't have the arbitrary field support of ChatMapper except for on Dialogue Entries. So there are still some limitations to keep in mind if your project has custom fields for characters or locations or anything like that.

That said, if you want a one-way editor, TalkerMaker should work for that as it is now.
