### ISSUE TITLE
TalkerMaker crashes when I click the file menu

### ISSUE THREAD

**Issue by volo-thomas** [digiwombat/TalkerMakerDeluxe#6]
Very strange problem here. As far as I can tell everything works except the file menu. If I click that it immediately brings up the windows program has stopped working dialog box.

I'm running Windows 10 creator update.

**Comment by digiwombat** [comment]
Yeah, the newest commit fixes that problem (no idea what was causing it, honestly).

If you know how to make a new build, you can build the latest commit and it should work fine. There are a lot of other minor issues that might be in, so I didn't do a new release.

Let me know if you can't do a new build and I'll make up a release (filled with warnings about how everything's VERY unchecked at this point, haha)

**Comment by digiwombat** [comment]
Alright! Fixed that up. It was an install location problem. Windows 10 really goes nuts with the Program Files lockdown. Installer now puts it in Local Appdata and solves the issue.
