### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by Cigam-HFden** [digiwombat/TalkerMakerDeluxe#9]
I am not currently on a windows machine, but your editor looks like a great visual editor for what I need to do. I was wondering if there was a way that you could compile it as a linux bin/run/appimage or some format that I can use? Personally I am on Fedora so it uses rpm files but an appimage is more universal across distros. Thanks.

**Comment by digiwombat** [comment]
Sadly, I am using WPF for the UI, and in spite of constant, repeated begging from the community neither the Mono Project nor Micrsoft's .NET Core have any plans to support WPF cross-platform.

The best I can suggest is giving it a try in Wine after installing dotnet support with winetricks. [Here's a potentially helpful reddit post on how to do this.](https://old.reddit.com/r/linux4noobs/comments/firqs9/getting_windows_wpf_applications_to_run_with_wine/)

So, my apologies, but considering WPF being the black sheep of the UI world and the deep reliance on it in the project I can't easily provide Linux support. I'm keeping an eye on [Avalonia](https://github.com/AvaloniaUI/Avalonia) but I don't think it provides drop-in support for most projects so it would likely require a large amount of rewrites. I may give it a look in the future.

Closing this, but feel free to open it back up for questions or comments if you have any specific wine-related bugs and I'll try my best to sort them out as I have time.

**Comment by digiwombat** [comment]
As a minor followup thought: It's probably way easier these days to just run a Windows VM than to try to get dotnet and WPF working with wine, so as crap an answer as that is, that's probably what I'd do personally.
